// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	wallet "backend/api/internal/handler/wallet"
	"backend/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/create",
				Handler: wallet.CreateWalletHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: wallet.LoginWalletHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/wallet"),
	)
}
