package types

//
//
//// Code generated by goctl. DO NOT EDIT.
//package types
//
//type CreateWalletReq struct {
//	Password string `json:"password" validate:"required"`
//}
//
//type LoginWalletReq struct {
//	Password          string `json:"password" validate:"required"`
//	EncryptedMnemonic string `json:"encrypted_mnemonic" validate:"required"`
//}
//
//type CreateWalletData struct {
//	Address  string `json:"address"`
//	Mnemonic string `json:"mnemonic"`
//}
//
//type WalletInfoData struct {
//	ID                int    `json:"id"`
//	Address           string `json:"address"`
//	EncryptedMnemonic string `json:"encrypted_mnemonic"`
//}
//
//type Response struct {
//	Code int         `json:"code"`
//	Msg  string      `json:"msg"`
//	Data interface{} `json:"data,omitempty"`
//}
